global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: 'amqp-server'
    static_configs:
      - targets: ['host.docker.internal:9419']
        labels:
          instance: 'amqp-local'
          environment: 'development'

